const firstNames = [
  'Walmart',
  'Amazon',
  'Apple',
  'Microsoft',
  'Alphabet (Google)',
  'Saudi Aramco',
  'Meta Platforms (Facebook)',
  'Berkshire Hathaway',
  'NVIDIA',
  'TSMC (Taiwan Semiconductor Manufacturing Company)',
  'JPMorgan Chase',
  'CVS Health',
  'Volkswagen Group',
  'ExxonMobil',
  'UnitedHealth Group',
  'Samsung Electronics',
  'Toyota',
  'Shell',
  'Costco',
  'Tencent',
  'Visa',
  'Mastercard',
  'Netflix',
  'Tesla',
  'Coca-Cola',
  'Nike',
  "McDonald's",
  'Mercedes-Benz',
  'IBM',
  'Intel',
  'Johnson & Johnson',
  'Procter & Gamble',
  'The Home Depot',
  'Bank of America',
  'Salesforce',
  'Oracle',
  'Cisco',
  'LVMH',
  'Unilever',
  'Starbucks',
  'Disney',
  'Accenture',
  'Qualcomm',
  'PepsiCo',
  'Adobe',
  'Goldman Sachs',
  'Morgan Stanley',
  'General Electric',
  'Alibaba',
  'Nestlé',
  'SAP',
]

const lastNames = [
  'Learning',
  'Library',
  'World',
  'Plus',
  'Prime',
  'Supreme',
  'Deluxe',
  'Study',
  'Kids',
  'Adults',
  'X',
  'Science',
  'Fantasy',
  'Fiction',
  'Horror',
  'Literature',
]

const names = {
  firstNames,
  lastNames,
}

export default names
